spring:
  output.ansi.enabled: ALWAYS

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jaeyeonling.boilerplate:
  application:
    name: boilerplate
    version: 1
  security:
    loginEndPoint: /login
    socialLoginEndPoint: /social-login/{authProvider}
    passwordEncodeStrength: 6
    authProviderEndPoints:
      kakao: https://kapi.kakao.com/v2/user/me
      github: https://api.github.com/user
  jwt:
    secretKey: SeCrEtKeY
    refreshTerm: 30s
    expiredTerm: 1m
    jwtIdLength: 128
    headerName: Authorization
    skipPaths:
      - /health
      - /timestamp
      - /login
    checkPaths:
      - /user
      - /admin
