spring:
  output.ansi.enabled: ALWAYS
  data-source:
    url: jdbc:mysql://127.0.0.1:3306/boilerplate?useUnicode=true&characterEncoding=UTF-8&useLocalSessionState=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server.port: 8080

jaeyeonling.boilerplate:
  application:
    name: boilerplate
    version: 1
  security:
    loginEndPoint: /login
    socialLoginEndPoint: /social-login/{authProvider}
    passwordEncodeStrength: 6
    authProviderEndPoints:
      kakao: https://kapi.kakao.com/v2/user/me
      github: https://api.github.com/user
      naver: https://openapi.naver.com/v1/nid/me
  jwt:
    secretKey: SeCrEtKeY
    refreshTerm: 30s
    expiredTerm: 1m
    jwtIdLength: 128
    headerName: Authorization
    skipPaths:
      - /health
      - /timestamp
      - /login
    checkPaths:
      - /user
      - /admin
